version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stock-flask
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_DEBUG: 1